[Arabic]
technical_name = "Arabic"
database_name = "AR"
deepl_name = "AR"
llm_name = "Arabic (Standard)"
picker_name = "Arabic ğŸ‡ªğŸ‡¬"
casual_name = "Arabic"
weblist_topname = "Arabic"
weblist_subname = "(Standard)"
flag_code = "EG"               # egypt is commonly used to represent standard arabic
supports_deepl = true
is_rtl = true
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "ar"
wiktionary_name = "Arabic"

[Bulgarian]
technical_name = "Bulgarian"
database_name = "BG"
deepl_name = "BG"
llm_name = "Bulgarian"
picker_name = "Bulgarian ğŸ‡§ğŸ‡¬"
casual_name = "Bulgarian"
weblist_topname = "Bulgarian"
flag_code = "BG"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "bg"
wiktionary_name = "Bulgarian"

[Chinese]
technical_name = "Chinese"
database_name = "ZH"
deepl_name = "ZH"
llm_name = "Chinese (Simplified)"
picker_name = "Chinese (Simplified) ğŸ‡¨ğŸ‡³"
casual_name = "Chinese"
weblist_topname = "Chinese"
weblist_subname = "(Simplified)"
flag_code = "CN"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = [{ category = "GOOD", text = "Optional Pinyin" }]
clientside_features = [
    { type = "binary", internal = "enablePinyin", display = "Pinyin", default = true },
    { type = "binary", internal = "fullPinyin", display = "Show Multiple Pinyins", default = false, predicated = "enablePinyin" },
]
wiktionary_code = "zh"
wiktionary_name = "Chinese"

[ChineseTraditional]
technical_name = "ChineseTraditional"
database_name = "ZH-HANT"
deepl_name = "ZH-HANT"
llm_name = "Chinese (Traditional)"
picker_name = "Chinese (Traditional) ğŸ‡¹ğŸ‡¼"
casual_name = "Chinese"
weblist_topname = "Chinese"
weblist_subname = "(Traditional)"
flag_code = "TW"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "zh"
wiktionary_name = "Chinese"

[Croatian]
technical_name = "Croatian"
database_name = "HR"
llm_name = "Croatian"
picker_name = "Croatian ğŸ‡­ğŸ‡·"
casual_name = "Croatian"
weblist_topname = "Croatian"
flag_code = "HR"
supports_deepl = false
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "sh"
wiktionary_name = "Serbo-Croatian"

[Czech]
technical_name = "Czech"
database_name = "CS"
deepl_name = "CS"
llm_name = "Czech"
picker_name = "Czech ğŸ‡¨ğŸ‡¿"
casual_name = "Czech"
weblist_topname = "Czech"
flag_code = "CZ"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "cs"
wiktionary_name = "Czech"

[Danish]
technical_name = "Danish"
database_name = "DA"
deepl_name = "DA"
llm_name = "Danish"
picker_name = "Danish ğŸ‡©ğŸ‡°"
casual_name = "Danish"
weblist_topname = "Danish"
flag_code = "DK"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "da"
wiktionary_name = "Danish"

[Dutch]
technical_name = "Dutch"
database_name = "NL"
deepl_name = "NL"
llm_name = "Dutch"
picker_name = "Dutch ğŸ‡³ğŸ‡±"
casual_name = "Dutch"
weblist_topname = "Dutch"
flag_code = "NL"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "nl"
wiktionary_name = "Dutch"

[Esperanto]
technical_name = "Esperanto"
database_name = "EO"
llm_name = "Esperanto"
picker_name = "Esperanto ğŸŸ¢"
casual_name = "Esperanto"
weblist_topname = "Esperanto"
flag_code = "EO"
supports_deepl = false
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "eo"
wiktionary_name = "Esperanto"

[Estonian]
technical_name = "Estonian"
database_name = "ET"
deepl_name = "ET"
llm_name = "Estonian"
picker_name = "Estonian ğŸ‡ªğŸ‡ª"
casual_name = "Estonian"
weblist_topname = "Estonian"
flag_code = "EE"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "et"
wiktionary_name = "Estonian"

[Finnish]
technical_name = "Finnish"
database_name = "FI"
deepl_name = "FI"
llm_name = "Finnish"
picker_name = "Finnish ğŸ‡«ğŸ‡®"
casual_name = "Finnish"
weblist_topname = "Finnish"
flag_code = "FI"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "fi"
wiktionary_name = "Finnish"

[French]
technical_name = "French"
database_name = "FR"
deepl_name = "FR"
llm_name = "French"
picker_name = "French ğŸ‡«ğŸ‡·"
casual_name = "French"
weblist_topname = "French"
flag_code = "FR"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "fr"
wiktionary_name = "French"

[German]
technical_name = "German"
database_name = "DE"
deepl_name = "DE"
llm_name = "German"
picker_name = "German ğŸ‡©ğŸ‡ª"
casual_name = "German"
weblist_topname = "German"
flag_code = "DE"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "de"
wiktionary_name = "German"

[Greek]
technical_name = "Greek"
database_name = "EL"
deepl_name = "EL"
llm_name = "Greek"
picker_name = "Greek ğŸ‡¬ğŸ‡·"
casual_name = "Greek"
weblist_topname = "Greek"
flag_code = "GR"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "el"
wiktionary_name = "Greek"

[Hebrew]
technical_name = "Hebrew"
database_name = "HE"
llm_name = "Hebrew"
picker_name = "Hebrew ğŸ‡®ğŸ‡±"
casual_name = "Hebrew"
weblist_topname = "Hebrew"
flag_code = "IL"
supports_deepl = false
is_rtl = true
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "he"
wiktionary_name = "Hebrew"

[Hindi]
technical_name = "Hindi"
database_name = "HI"
llm_name = "Hindi"
picker_name = "Hindi ğŸ‡®ğŸ‡³"
casual_name = "Hindi"
weblist_topname = "Hindi"
flag_code = "IN"
supports_deepl = false
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "hi"
wiktionary_name = "Hindi"

[Hungarian]
technical_name = "Hungarian"
database_name = "HU"
deepl_name = "HU"
llm_name = "Hungarian"
picker_name = "Hungarian ğŸ‡­ğŸ‡º"
casual_name = "Hungarian"
weblist_topname = "Hungarian"
flag_code = "HU"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "hu"
wiktionary_name = "Hungarian"

[Indonesian]
technical_name = "Indonesian"
database_name = "ID"
deepl_name = "ID"
llm_name = "Indonesian"
picker_name = "Indonesian ğŸ‡®ğŸ‡©"
casual_name = "Indonesian"
weblist_topname = "Indonesian"
flag_code = "ID"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "id"
wiktionary_name = "Indonesian"

[Italian]
technical_name = "Italian"
database_name = "IT"
deepl_name = "IT"
llm_name = "Italian"
picker_name = "Italian ğŸ‡®ğŸ‡¹"
casual_name = "Italian"
weblist_topname = "Italian"
flag_code = "IT"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "it"
wiktionary_name = "Italian"

[Japanese]
technical_name = "Japanese"
database_name = "JA"
deepl_name = "JA"
llm_name = "Japanese"
picker_name = "Japanese ğŸ‡¯ğŸ‡µ"
casual_name = "Japanese"
weblist_topname = "Japanese"
flag_code = "JP"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = [{ category = "GOOD", text = "Optional Furigana" }]
clientside_features = [
    { type = "binary", internal = "enableFurigana", display = "Furigana", default = true },
]
wiktionary_code = "ja"
wiktionary_name = "Japanese"

[Korean]
technical_name = "Korean"
database_name = "KO"
deepl_name = "KO"
llm_name = "Korean"
picker_name = "Korean ğŸ‡°ğŸ‡·"
casual_name = "Korean"
weblist_topname = "Korean"
flag_code = "KR"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "ko"
wiktionary_name = "Korean"

[LatinClassical]
technical_name = "LatinClassical"
database_name = "LA"
llm_name = "Latin (Classical)"
picker_name = "Latin (Classical) ğŸ›ï¸ğŸ¦…"
casual_name = "Latin"
weblist_topname = "Latin"
weblist_subname = "(Classical)"
flag_code = "LA_nb"
supports_deepl = false
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "la"
wiktionary_name = "Latin"

[Latvian]
technical_name = "Latvian"
database_name = "LV"
deepl_name = "LV"
llm_name = "Latvian"
picker_name = "Latvian ğŸ‡±ğŸ‡»"
casual_name = "Latvian"
weblist_topname = "Latvian"
flag_code = "LV"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "lv"
wiktionary_name = "Latvian"

[Lithuanian]
technical_name = "Lithuanian"
database_name = "LT"
deepl_name = "LT"
llm_name = "Lithuanian"
picker_name = "Lithuanian ğŸ‡±ğŸ‡¹"
casual_name = "Lithuanian"
weblist_topname = "Lithuanian"
flag_code = "LT"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "lt"
wiktionary_name = "Lithuanian"

[Norwegian]
technical_name = "Norwegian"
database_name = "NB"
deepl_name = "NB"
llm_name = "Norwegian"
picker_name = "Norwegian ğŸ‡³ğŸ‡´"
casual_name = "Norwegian"
weblist_topname = "Norwegian"
flag_code = "NO"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "no"
wiktionary_name = "Norwegian"

[Persian]
technical_name = "Persian"
database_name = "FA"
llm_name = "Persian"
picker_name = "Persian ğŸ‡®ğŸ‡·"
casual_name = "Persian"
weblist_topname = "Persian"
flag_code = "IR"
supports_deepl = false
is_rtl = true
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "fa"
wiktionary_name = "Persian"

[Polish]
technical_name = "Polish"
database_name = "PL"
deepl_name = "PL"
llm_name = "Polish"
picker_name = "Polish ğŸ‡µğŸ‡±"
casual_name = "Polish"
weblist_topname = "Polish"
flag_code = "PL"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "pl"
wiktionary_name = "Polish"

[PortugueseBrazil]
technical_name = "PortugueseBrazil"
database_name = "PT-BR"
deepl_name = "PT-BR"
llm_name = "Portuguese (Brazil)"
picker_name = "Portuguese (BR) ğŸ‡§ğŸ‡·"
casual_name = "Portuguese"
weblist_topname = "Portuguese"
weblist_subname = "(Brazil)"
flag_code = "BR"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "pt-BR"
wiktionary_name = "Portuguese (Brazil)"

[PortuguesePortugal]
technical_name = "PortuguesePortugal"
database_name = "PT-PT"
deepl_name = "PT-PT"
llm_name = "Portuguese (Portugal)"
picker_name = "Portuguese (PT) ğŸ‡µğŸ‡¹"
casual_name = "Portuguese"
weblist_topname = "Portuguese"
weblist_subname = "(Portugal)"
flag_code = "PT"
supports_deepl = true
is_rtl = false
supports_dicts = false
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "pt-PT"
wiktionary_name = "Portuguese (Portugal)"

[Romanian]
technical_name = "Romanian"
database_name = "RO"
deepl_name = "RO"
llm_name = "Romanian"
picker_name = "Romanian ğŸ‡·ğŸ‡´"
casual_name = "Romanian"
weblist_topname = "Romanian"
flag_code = "RO"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "ro"
wiktionary_name = "Romanian"

[Russian]
technical_name = "Russian"
database_name = "RU"
deepl_name = "RU"
llm_name = "Russian"
picker_name = "Russian ğŸ‡·ğŸ‡º"
casual_name = "Russian"
weblist_topname = "Russian"
flag_code = "RU"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "ru"
wiktionary_name = "Russian"

# was previously "Slovakian", it turns out that's not the preferred form
# I've changed the public-facing bits while keeping the technical side the same
[Slovakian]
technical_name = "Slovakian"
database_name = "SK"
deepl_name = "SK"
llm_name = "Slovak"
picker_name = "Slovak ğŸ‡¸ğŸ‡°"
casual_name = "Slovak"
weblist_topname = "Slovak"
flag_code = "SK"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "sk"
wiktionary_name = "Slovak"

[Slovenian]
technical_name = "Slovenian"
database_name = "SL"
deepl_name = "SL"
llm_name = "Slovenian"
picker_name = "Slovenian ğŸ‡¸ğŸ‡®"
casual_name = "Slovenian"
weblist_topname = "Slovenian"
flag_code = "SI"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "sl"
wiktionary_name = "Slovenian"

[Spanish]
technical_name = "Spanish"
database_name = "ES"
deepl_name = "ES"
llm_name = "Spanish"
picker_name = "Spanish ğŸ‡ªğŸ‡¸"
casual_name = "Spanish"
weblist_topname = "Spanish"
flag_code = "ES"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "es"
wiktionary_name = "Spanish"

[Swedish]
technical_name = "Swedish"
database_name = "SV"
deepl_name = "SV"
llm_name = "Swedish"
picker_name = "Swedish ğŸ‡¸ğŸ‡ª"
casual_name = "Swedish"
weblist_topname = "Swedish"
flag_code = "SE"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "sv"
wiktionary_name = "Swedish"

[Turkish]
technical_name = "Turkish"
database_name = "TR"
deepl_name = "TR"
llm_name = "Turkish"
picker_name = "Turkish ğŸ‡¹ğŸ‡·"
casual_name = "Turkish"
weblist_topname = "Turkish"
flag_code = "TR"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = false
additional_tags = []
clientside_features = []
wiktionary_code = "tr"
wiktionary_name = "Turkish"

[Ukrainian]
technical_name = "Ukrainian"
database_name = "UK"
deepl_name = "UK"
llm_name = "Ukrainian"
picker_name = "Ukrainian ğŸ‡ºğŸ‡¦"
casual_name = "Ukrainian"
weblist_topname = "Ukrainian"
flag_code = "UA"
supports_deepl = true
is_rtl = false
supports_dicts = true
prefers_dicts = true
additional_tags = []
clientside_features = []
wiktionary_code = "uk"
wiktionary_name = "Ukrainian"
